# Site settings
title: Алексей Филимонов
description: Дз Git pages
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Алексей Филимонов
user_description: учусь в Нетологии, окончил курс Основы Java
user_title: специальность андроид-разработчик
email: zeroco0l@inbox.ru
# twitter_username: lorem_ipsum
# instagram_username: zeroco0l2022
# facebook_username: zeroco0l2022
# linkedin_username: zeroco0l2022
github_username:  zeroco0l2022
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

